config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :equipment
  resources :weapons, controller: :equipment, only: [:create, :update, :show, :destroy]
  resources :shields, controller: :equipment, only: [:create, :update, :show, :destroy]
  resources :fighters
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :fights, only: [:new, :create, :index, :show]
  root 'fights#new'
end

app/models/fighter.rb
class Fighter < ApplicationRecord
  has_many :fight_participations, dependent: :destroy
  has_many :fights, through: :fight_participations
  has_many :wins, class_name: "Fight", foreign_key: "winner_id", dependent: :destroy

  has_one_attached :avatar, dependent: :purge_later

  accepts_nested_attributes_for :fight_participations
  before_save :max_experience


  # check if the expiriense in the limit
  def max_experience
    if self.experience_points.present?
      self.experience_points = 1000 if self.experience_points > 1000
    else
      self.experience_points = 0
    end
  end

  def wins_fight
    return 0 unless self.fights.exists?
    self.wins.count
  end

  def lost_fight
    return 0 unless self.fights.exists?
    self.fights.count- wins_fight
  end
end

app/controllers/fighters_controller.rb
class FightersController < ApplicationController
  before_action :set_fighter, only: %i[ show edit update destroy ]

  # GET /fighters
  def index
    if params[:id].present?
      fighters = Fighter.where.not(id: params[:id])
      render :json => fighters.pluck(:id, :name)
    else
      @fighters = Fighter.all
    end
  end

  # GET /fighters/1
  def show
  end

  # GET /fighters/new
  def new
    @fighter = Fighter.new
  end

  # GET /fighters/1/edit
  def edit
  end

  # POST /fighters
  def create
    @fighter = Fighter.new(fighter_params)

    respond_to do |format|
      if @fighter.save
        format.html { redirect_to @fighter, notice: "fighter creé" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fighters/1
  def update
    respond_to do |format|
      if @fighter.update(fighter_params)
        format.html { redirect_to @fighter, notice: "fighter modifié" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fighters/1
  def destroy
    @fighter.destroy
    respond_to do |format|
      format.html { redirect_to fighters_url, notice: "fighter supprimé" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fighter
      @fighter = Fighter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fighter_params
      params.require(:fighter).permit(:name, :life_points, :attack_points, :experience_points, :avatar)
    end


end

app/helpers/fighters_helper.rb
module FightersHelper
end

app/views/fighters/_form.html.haml
%section.section.pt-0
  .row
    .col-lg-12
      .card.pt-4
        .card-body
          = form_for @fighter do |f|
            .mb-3
              = f.label :avatar, class: "form-label"
              = f.file_field :avatar, class: "form-control"
            .mb-3
              = f.label :name, class: "form-label"
              = f.text_field :name, class: "form-control", required: :true
            .mb-3
              = f.label :life_points, class: "form-label"
              = f.number_field :life_points, class: "form-control", required: :true
            .mb-3
              = f.label :attack_points, class: "form-label"
              = f.number_field :attack_points, class: "form-control", required: :true, min: 1
            .mb-3
              = f.label :experience_points, class: "form-label"
              = f.number_field :experience_points, class: "form-control", required: :true
            .mb-3
              = f.submit "sauvegarder", class: "btn btn-primary"

app/views/fighters/edit.html.haml
= render '/partials/navbar'
%main#main.main
  .overlay
  .pagetitle
    %h1 Modifier Combattant
    %nav
      %ol.breadcrumb
        %li.breadcrumb-item
          %a{href: "/fights/new"} Arena
        %li.breadcrumb-item
          %a{href: "/fighters"} Combattants
        %li.breadcrumb-item.active Combattant
  = render 'form'

app/views/fighters/index.html.haml
= render '/partials/navbar'
%main#main.main
  .overlay
  .pagetitle
    %h1 Liste des combattants
    = link_to "Ajouter combattant", new_fighter_path(), :class => "btn btn-primary float-end"
    %nav
      %ol.breadcrumb
        %li.breadcrumb-item
          %a{href: "/fights/new"} Arena
        %li.breadcrumb-item.active combattants
  %section.section.pt-0
    .row
      .col-lg-12
        .card.pt-4
          .card-body
            %table.table.datatable.table-hover{style: "width:100%"}
              %thead
                %tr
                  %th{scope: "col"} Nom
                  %th{scope: "col"} Point de vie
                  %th{scope: "col"} Point d'attaque
                  %th{scope: "col"} Point d'experience
                  %th{scope: "col"} Victoires
                  %th{scope: "col"} Défaites
                  %th{scope: "col"} Afficher
                  %th{scope: "col"} Modifier
                  %th{scope: "col"} Supprimer
              %tbody
                - @fighters.each do |fighter|
                  %tr
                    %td= fighter.name
                    %td= fighter.life_points
                    %td= fighter.attack_points
                    %td= fighter.experience_points
                    %td= fighter.wins_fight
                    %td= fighter.lost_fight
                    %td
                      =link_to fighter do
                        %i.fa-solid.fa-file
                    %td
                      =link_to  edit_fighter_path(fighter) do
                        %i.fa-solid.fa-pen-to-square
                    %td
                      =link_to fighter, method: :delete, data: { confirm: "confirmer" } do
                        %i.fa-solid.fa-trash-can

app/views/fighters/new.html.haml
= render '/partials/navbar'
%main#main.main
  .overlay
  .pagetitle
    %h1 Ajouter Combattant
    %nav
      %ol.breadcrumb
        %li.breadcrumb-item
          %a{href: "/fights/new"} Arena
        %li.breadcrumb-item
          %a{href: "/fighters"} Combattants
        %li.breadcrumb-item.active Combattant
  = render 'form'

app/views/fighters/show.html.haml
= render '/partials/navbar'
%main#main.main
  .overlay
  .pagetitle
    %h1 Afficher Combattant
    %nav
      %ol.breadcrumb
        %li.breadcrumb-item
          %a{href: "/fights/new"} Arena
        %li.breadcrumb-item
          %a{href: "/fighters"} Combattants
        %li.breadcrumb-item.active Combattant
  %section.section.pt-0
    .row
      .col-lg-12
        .card.pt-4
          .card-body
            .row.mb-3
              .col-xl-5.col-lg-5.col-md-6.col-sm-12.col-xs-12
                .card.border-gray-300
                  .card-header.bg-primary.bg-gradient.text-white.border-dark-subtle
                    .d-flex.justify-content-between.align-baseline.fs-5
                      %span.align-baseline.fs-5
                        = @fighter.name
                      = link_to edit_fighter_path(@fighter), title: "Modifier", class:"pull-right" do
                        %i.fa-solid.fa-pen-to-square{"aria-hidden" => "true", style: "color: white;"}
                  .card-body.text-white.fs-6.p-3
                    %ul.list-group.list-group-flush.price-list
                      %li.list-group-item.border-secondary-subtle
                        %p
                          %span.fw-semibold
                            - if @fighter.avatar.attached?
                              = image_tag @fighter.avatar.variant(resize_to_fill: [100, 100])
                            - else
                              %svg{height: "4em", viewbox: "0 0 448 512", xmlns: "http://www.w3.org/2000/svg"}
                                %path{d: "M224 256c-57.2 0-105.6-37.5-122-89.3c-1.1 1.3-2.2 2.6-3.5 3.8c-15.8 15.8-38.8 20.7-53.6 22.1c-8.1 .8-14.6-5.7-13.8-13.8c1.4-14.7 6.3-37.8 22.1-53.6c5.8-5.8 12.6-10.1 19.6-13.4c-7-3.2-13.8-7.6-19.6-13.4C37.4 82.7 32.6 59.7 31.1 44.9c-.8-8.1 5.7-14.6 13.8-13.8c14.7 1.4 37.8 6.3 53.6 22.1c4.8 4.8 8.7 10.4 11.7 16.1C131.4 28.2 174.4 0 224 0c70.7 0 128 57.3 128 128s-57.3 128-128 128zM0 482.3C0 399.5 56.4 330 132.8 309.9c6-1.6 12.2 .9 15.9 5.8l62.5 83.3c6.4 8.5 19.2 8.5 25.6 0l62.5-83.3c3.7-4.9 9.9-7.4 15.9-5.8C391.6 330 448 399.5 448 482.3c0 16.4-13.3 29.7-29.7 29.7H29.7C13.3 512 0 498.7 0 482.3zM160 96c-8.8 0-16 7.2-16 16s7.2 16 16 16H288c8.8 0 16-7.2 16-16s-7.2-16-16-16H160z"}
                      %li.list-group-item.border-secondary-subtle
                        %p
                          %span.fw-semibold
                            Nom:
                          = @fighter.name
                      %li.list-group-item.border-secondary-subtle
                        %span.fw-semibold
                          Point de vie:
                        = @fighter.life_points
                      %li.list-group-item.border-secondary-subtle
                        %span.fw-semibold
                          Attaque:
                        = @fighter.attack_points
                      %li.list-group-item.border-secondary-subtle
                        %span.fw-semibold
                          Niveau:
                        = @fighter.experience_points
              .col-xl-5.col-lg-5.col-md-6.col-sm-12.col-xs-12
                .row
                  %p
                    %span.fw-semibold
                      Victoires:
                    = @fighter.wins_fight
                  %p.float-end
                    %span.fw-semibold
                      Défaites:
                    = @fighter.lost_fight