config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :equipment
  resources :weapons, controller: :equipment, only: [:create, :update, :show, :destroy]
  resources :shields, controller: :equipment, only: [:create, :update, :show, :destroy]
  resources :fighters
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :fights, only: [:new, :create, :index, :show]
  root 'fights#new'
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_many :fight_participation_equipment, dependent: :destroy
  has_many :fight_participations, through: :fight_participation_equipment

  scope :weapon, -> { where(type: "Weapon") }
  scope :shield, -> { where(type: "Shield") }
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_action :set_equipment, only: %i[ show edit update destroy ]

  # GET /equipments
  def index
    if params[:type] == "Weapon"
      @equipment = Weapon.all
    elsif params[:type] == "Shield"
      @equipment = Shield.all
    else
      @equipment = Equipment.all
    end
  end

  # GET /equipments/1
  def show
  end

  # GET /equipments/new
  def new
    @equipment = Equipment.new
  end

  # GET /equipments/1/edit
  def edit
  end

  # POST /equipments
  def create
    if params[:weapon].present?
      @equipment = Weapon.new(weapon_params)
    elsif params[:shield].present?
      @equipment = Shield.new(shield_params)
    else
      @equipment = Equipment.new(equipment_params)
    end

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to @equipment, notice: "equipment crée" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipments/1
  def update
    respond_to do |format|
      if @equipment.update(send("#{@equipment.class.name.downcase}_params"))
        format.html { redirect_to @equipment, notice: "equipement modifier" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipments/1
  def destroy
    @equipment.destroy
    respond_to do |format|
      format.html { redirect_to equipment_index_path(type: @equipment.class.name), notice: "equipement supprimer" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment
      @equipment = Equipment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def equipment_params
      params.require(:equipment).permit(:name, :attack_points, :defense_points, :type)
    end

    # Only allow a list of trusted parameters through.
    def weapon_params
      params.require(:weapon).permit(:name, :attack_points, :defense_points)
    end

    # Only allow a list of trusted parameters through.
    def shield_params
      params.require(:shield).permit(:name, :defense_points)
    end
end

app/helpers/equipments_helper.rb
module EquipmentsHelper
end

app/views/equipment/_form.html.haml
%section.section.pt-0
  .row
    .col-lg-12
      .card.pt-4
        .card-body
          = form_for @equipment do |f|
            .mb-3
              = f.label :name, class: "form-label"
              = f.text_field :name, class: "form-control", required: :true
            .mb-3
              = f.label :attack_points, class: "form-label"
              = f.number_field :attack_points, class: "form-control", required: :true
            .mb-3
              = f.label :defense_points, class: "form-label"
              = f.number_field :defense_points, class: "form-control", required: :true
            .mb-3
              = f.label :type, class: "form-label"
              = f.select :type, options_for_select([Weapon.name, Shield.name], @equipment.type), {}, class: "form-control"
            .mb-3
              = f.submit "sauvegarder", class: "btn btn-primary"

app/views/equipment/edit.html.haml
= render '/partials/navbar'
%main#main.main
  .overlay
  .pagetitle
    %h1 Modifier Equipement
    %nav
      %ol.breadcrumb
        %li.breadcrumb-item
          %a{href: "/fights/new"} Arena
        %li.breadcrumb-item
          %a{href: "/equipment"} Equipements
        %li.breadcrumb-item.active Equipement
  = render 'form'

app/views/equipment/index.html.haml
= render '/partials/navbar'
%main#main.main
  .overlay
  .pagetitle
    %h1 Liste des equipements
    = link_to 'Ajouter equipement', new_equipment_path(), :class => "btn btn-primary float-end"

    %nav
      %ol.breadcrumb
        %li.breadcrumb-item
          %a{href: "/fights/new"} Arena
        %li.breadcrumb-item.active equipements
  %section.section.pt-0
    .row
      .col-lg-12
        .card.pt-4
          .card-body
            %table.table.datatable.table-hover{style: "width:100%"}
              %thead
                %tr
                  %th{scope: "col"} Nom
                  %th{scope: "col"} Point d'attaque
                  %th{scope: "col"} Point de defense
                  %th{scope: "col"} Type
                  %th{scope: "col"} Afficher
                  %th{scope: "col"} Modifier
                  %th{scope: "col"} Supprimer
              %tbody
                - @equipment.each do |equipment|
                  %tr
                    %td= equipment.name
                    %td= equipment.attack_points
                    %td= equipment.defense_points
                    %td= equipment.type
                    %td
                      =link_to equipment_path(equipment, type: params[:type]) do
                        %i.fa-solid.fa-file
                    %td
                      =link_to edit_equipment_path(equipment, type: params[:type]) do
                        %i.fa-solid.fa-pen-to-square
                    %td
                      = link_to equipment, method: :delete, data: { confirm: "confirmer" } do
                        %i.fa-solid.fa-trash-can

app/views/equipment/new.html.haml
= render '/partials/navbar'
%main#main.main
  .overlay
  .pagetitle
    %h1 Ajouter Equipement
    %nav
      %ol.breadcrumb
        %li.breadcrumb-item
          %a{href: "/fights/new"} Arena
        %li.breadcrumb-item
          %a{href: "/equipment"} Equipements
        %li.breadcrumb-item.active Equipement
  = render 'form'

app/views/equipment/show.html.haml
= render '/partials/navbar'
%main#main.main
  .overlay
  .pagetitle
    %h1 Afficher equipement
    %nav
      %ol.breadcrumb
        %li.breadcrumb-item
          %a{href: "/fights/new"} Arena
        %li.breadcrumb-item
          %a{href: "/equipment"} Equipements
        %li.breadcrumb-item.active Equipement
  %section.section.pt-0
    .row
      .col-lg-12
        .card.pt-4
          .card-body
            .col-xl-3.col-lg-4.col-md-6.col-sm-12.col-xs-12
              .card.border-gray-300
                .card-header.bg-primary.bg-gradient.text-white.border-dark-subtle
                  .d-flex.justify-content-between.align-baseline.fs-5
                    %span.align-baseline.fs-5
                      = @equipment.name
                    = link_to edit_equipment_path(@equipment), title: "Modifier", class:"pull-right" do
                      %i.fa-solid.fa-pen-to-square{"aria-hidden" => "true", style: "color: white;"}
                .card-body.text-white.fs-6.p-3
                  %ul.list-group.list-group-flush.price-list
                    %li.list-group-item.border-secondary-subtle
                      %p
                        %span.fw-semibold
                          Nom:
                        = @equipment.name
                    %li.list-group-item.border-secondary-subtle
                      %span.fw-semibold
                        Attaque:
                      = @equipment.attack_points
                    %li.list-group-item.border-secondary-subtle
                      %span.fw-semibold
                        Défense:
                      = @equipment.defense_points
                    %li.list-group-item.border-secondary-subtle
                      %span.fw-semibold
                        Type:
                      = @equipment.type