config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :equipment
  resources :weapons, controller: :equipment, only: [:create, :update, :show, :destroy]
  resources :shields, controller: :equipment, only: [:create, :update, :show, :destroy]
  resources :fighters
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :fights, only: [:new, :create, :index, :show]
  root 'fights#new'
end

app/models/fight.rb
class Fight < ApplicationRecord
  belongs_to :winner, class_name: "Fighter", optional: true
  has_many :fight_participations, dependent: :destroy
  has_many :fighters, through: :fight_participations
  has_many :hits, through: :fight_participations, dependent: :destroy
  accepts_nested_attributes_for :fight_participations

end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  before_action :set_fight, only: :show

  # GET /fights
  def index
    @fights = Fight.all.order(created_at: :desc)
  end

  # GET /fights/1
  def show
  end

  # GET /fights/new
  def new
    @fight = Fight.new
    2.times { @fight.fight_participations.build }
  end

  # POST /fights
  def create
    @fight = Fight.new(fight_params)
    respond_to do |format|
      if @fight.save && battle(@fight)
        format.html { redirect_to @fight }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def battle(fight)
    offset = rand(fight.fight_participations.count)
    hitter_participation_first = fight.fight_participations.offset(offset).first
    hitter_participation_second = fight.fight_participations.where.not(id: hitter_participation_first.id).first
    while hitter_participation_first.full_life_points > 0 && hitter_participation_second.full_life_points > 0
      hit = hitter_participation_first.hits.create()
      hitter_participation_second.full_life_points -= hit.damage
      if hitter_participation_second.full_life_points > 0
        hit = hitter_participation_second.hits.create()
        hitter_participation_first.full_life_points -= hit.damage
      end
    end
    if hitter_participation_first.full_life_points > 0
      fight.update(winner: hitter_participation_first.fighter)
      winner = hitter_participation_first.fighter
      loser = hitter_participation_second.fighter
    else
      fight.update(winner: hitter_participation_second.fighter)
      winner = hitter_participation_second.fighter
      loser = hitter_participation_first.fighter
    end
    winner.update(experience_points: winner.experience_points + 2)
    loser.update(experience_points: loser.experience_points + 1)
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_fight
      @fight = Fight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fight_params
      params.require(:fight).permit(
        fight_participations_attributes: [
          :fighter_id,
          fight_participation_weapons_attributes: [
            :equipment_id
          ],
          fight_participation_shields_attributes: [
            :equipment_id
          ]
        ]
      )
    end
end

app/helpers/fights_helper.rb
module FightsHelper
end

app/views/fights/_fight_participation_shield_fields.html.haml
.nested-fields
  .mb-3.row.align-items-center
    .col
      = f.select :equipment_id, Shield.all.map{|e| [e.name, e.id]}, {:include_blank => "choisir votre Bouclier"}, class: "form-control", required: true
    .col-md-1
      = link_to_remove_association  f do
        %i.fa-solid.fa-minus

app/views/fights/_fight_participation_weapon_fields.html.haml
.nested-fields
  .mb-3.row.align-items-center
    .col
      = f.select :equipment_id, Weapon.all.map{|e| [e.name, e.id]}, {:include_blank => "choisir votre Arme"}, class: "form-control", required: true
    .col-md-1
      = link_to_remove_association  f do
        %i.fa-solid.fa-minus

app/views/fights/index.html.haml
= render '/partials/navbar'
%main#main.main
  .overlay
  .pagetitle
    %h1 Liste des combats
    %nav
      %ol.breadcrumb
        %li.breadcrumb-item
          %a{href: "/fights/new"} Arena
        %li.breadcrumb-item.active Combats
  %section.section.pt-0
    .row
      .col-lg-12
        .card.pt-4
          .card-body
            %table.table.datatable.table-hover{style: "width:100%"}
              %thead
                %tr
                  %th= "Combattant 1"
                  %th= "Combattant 2"
                  %th= "Date de Combat"
                  %th= "Historique"
              %tbody
                - @fights.each do |fight|
                  %tr
                    %td
                      - if fight.fighters.first.avatar.attached?
                        = image_tag fight.fighters.first.avatar.variant(resize_to_fill: [60, 60])
                      - else
                        %svg{height: "4em", viewbox: "0 0 448 512", xmlns: "http://www.w3.org/2000/svg"}
                          %path{d: "M224 256c-57.2 0-105.6-37.5-122-89.3c-1.1 1.3-2.2 2.6-3.5 3.8c-15.8 15.8-38.8 20.7-53.6 22.1c-8.1 .8-14.6-5.7-13.8-13.8c1.4-14.7 6.3-37.8 22.1-53.6c5.8-5.8 12.6-10.1 19.6-13.4c-7-3.2-13.8-7.6-19.6-13.4C37.4 82.7 32.6 59.7 31.1 44.9c-.8-8.1 5.7-14.6 13.8-13.8c14.7 1.4 37.8 6.3 53.6 22.1c4.8 4.8 8.7 10.4 11.7 16.1C131.4 28.2 174.4 0 224 0c70.7 0 128 57.3 128 128s-57.3 128-128 128zM0 482.3C0 399.5 56.4 330 132.8 309.9c6-1.6 12.2 .9 15.9 5.8l62.5 83.3c6.4 8.5 19.2 8.5 25.6 0l62.5-83.3c3.7-4.9 9.9-7.4 15.9-5.8C391.6 330 448 399.5 448 482.3c0 16.4-13.3 29.7-29.7 29.7H29.7C13.3 512 0 498.7 0 482.3zM160 96c-8.8 0-16 7.2-16 16s7.2 16 16 16H288c8.8 0 16-7.2 16-16s-7.2-16-16-16H160z"}
                      = fight.fighters.first.name
                      - if fight.winner == fight.fighters.first
                        %span.badge.bg-info
                          %i.fa-solid.fa-trophy
                      -else
                        %span.badge.bg-warning
                          %i.fa-solid.fa-face-frown
                    %td
                      - if fight.fighters.last.avatar.attached?
                        = image_tag fight.fighters.last.avatar.variant(resize_to_fill: [60, 60])
                      - else
                        %svg{height: "4em", viewbox: "0 0 448 512", xmlns: "http://www.w3.org/2000/svg"}
                          %path{d: "M224 256c-57.2 0-105.6-37.5-122-89.3c-1.1 1.3-2.2 2.6-3.5 3.8c-15.8 15.8-38.8 20.7-53.6 22.1c-8.1 .8-14.6-5.7-13.8-13.8c1.4-14.7 6.3-37.8 22.1-53.6c5.8-5.8 12.6-10.1 19.6-13.4c-7-3.2-13.8-7.6-19.6-13.4C37.4 82.7 32.6 59.7 31.1 44.9c-.8-8.1 5.7-14.6 13.8-13.8c14.7 1.4 37.8 6.3 53.6 22.1c4.8 4.8 8.7 10.4 11.7 16.1C131.4 28.2 174.4 0 224 0c70.7 0 128 57.3 128 128s-57.3 128-128 128zM0 482.3C0 399.5 56.4 330 132.8 309.9c6-1.6 12.2 .9 15.9 5.8l62.5 83.3c6.4 8.5 19.2 8.5 25.6 0l62.5-83.3c3.7-4.9 9.9-7.4 15.9-5.8C391.6 330 448 399.5 448 482.3c0 16.4-13.3 29.7-29.7 29.7H29.7C13.3 512 0 498.7 0 482.3zM160 96c-8.8 0-16 7.2-16 16s7.2 16 16 16H288c8.8 0 16-7.2 16-16s-7.2-16-16-16H160z"}

                      = fight.fighters.last.name
                      - if fight.winner == fight.fighters.last
                        %span.badge.bg-info
                          %i.fa-solid.fa-trophy
                      -else
                        %span.badge.bg-warning
                          %i.fa-solid.fa-face-frown
                    %td
                      = fight.created_at
                    %td
                      = link_to fight_path(fight) do
                        %i.fa-solid.fa-file-lines

app/views/fights/new.html.haml
= render '/partials/navbar'
%main#main.main
  .overlay
  .home_title
    %h1 Creer votre Combat
  %section.section.pt-0
  .row
    .col-lg-12
      .card.pt-4
        .card-body
          = form_for @fight do |f|
            .row.mb-3
              = f.fields_for :fight_participations do |participations_f|
                .col-xl-5.col-lg-5.col-md-5.col-sm-12.col-xs-12
                  .card.border-gray-300
                    .card-header.bg-primary.bg-gradient.text-white.border-dark-subtle
                      .d-flex.justify-content-between.align-baseline.fs-5
                        %span.align-baseline.fs-5
                          = "Combattant"
                          = participations_f.index + 1
                    .card-body.text-white.fs-6.p-3
                      %ul.list-group.list-group-flush.price-list
                        %li.list-group-item.border-secondary-subtle
                          %p
                            = participations_f.label :fighter_id, "Combattant:", class: "form-label"
                            = participations_f.select :fighter_id, Fighter.all.map{|f| [f.name, f.id]}, {:include_blank => "Choisir Votre Combattant"}, class: "form-control", id: "select_fighter_#{participations_f.index}", required: :true
                        %li.list-group-item.border-secondary-subtle
                          %p
                            %label.form-label= "Armes:"
                            = participations_f.fields_for :fight_participation_weapons do |participation_weapon_f|
                              = render "fight_participation_weapon_fields", f: participation_weapon_f
                            .links.text-center
                              = link_to_add_association  participations_f, :fight_participation_weapons do
                                %i.fa-solid.fa-plus
                        %li.list-group-item.border-secondary-subtle
                          %p
                            %label.form-label= "Boucliers:"
                            = participations_f.fields_for :fight_participation_shields do |participation_shield_f|
                              = render "fight_participation_shield_fields", f: participation_shield_f
                            .links.text-center
                              = link_to_add_association participations_f, :fight_participation_shields do
                                %i.fa-solid.fa-plus
                - if participations_f.index.zero?
                  .col-md-2.align-self-center.text-center
                    VS
            .mb-3.text-center
              = f.submit 'au combat', class: "btn btn-primary"

app/views/fights/show.html.haml
= render '/partials/navbar'
%main#main.main
  .overlay
  .pagetitle
    %h1 Afficher Combat
    %nav
      %ol.breadcrumb
        %li.breadcrumb-item
          %a{href: "/fights/new"} Arena
        %li.breadcrumb-item
          %a{href: "/fights"} Combats
        %li.breadcrumb-item.active Combat
  %section.section.pt-0
    .row
      .col-lg-12
        .card.pt-4
          .card-body
            .row.mb-3
              - @fight.fight_participations.each_with_index do |fight_participation, index|
                .col-xl-5.col-lg-5.col-md-5.col-sm-12.col-xs-12
                  .card.border-gray-300
                    .card-header.bg-primary.bg-gradient.text-white.border-dark-subtle
                      .d-flex.justify-content-between.align-baseline.fs-5
                        %span.align-baseline.fs-5
                          - if fight_participation.fighter.avatar.attached?
                            = image_tag fight_participation.fighter.avatar.variant(resize_to_fill: [80, 80])
                          - else
                            %svg{height: "4em", viewbox: "0 0 448 512", xmlns: "http://www.w3.org/2000/svg"}
                              %path{d: "M224 256c-57.2 0-105.6-37.5-122-89.3c-1.1 1.3-2.2 2.6-3.5 3.8c-15.8 15.8-38.8 20.7-53.6 22.1c-8.1 .8-14.6-5.7-13.8-13.8c1.4-14.7 6.3-37.8 22.1-53.6c5.8-5.8 12.6-10.1 19.6-13.4c-7-3.2-13.8-7.6-19.6-13.4C37.4 82.7 32.6 59.7 31.1 44.9c-.8-8.1 5.7-14.6 13.8-13.8c14.7 1.4 37.8 6.3 53.6 22.1c4.8 4.8 8.7 10.4 11.7 16.1C131.4 28.2 174.4 0 224 0c70.7 0 128 57.3 128 128s-57.3 128-128 128zM0 482.3C0 399.5 56.4 330 132.8 309.9c6-1.6 12.2 .9 15.9 5.8l62.5 83.3c6.4 8.5 19.2 8.5 25.6 0l62.5-83.3c3.7-4.9 9.9-7.4 15.9-5.8C391.6 330 448 399.5 448 482.3c0 16.4-13.3 29.7-29.7 29.7H29.7C13.3 512 0 498.7 0 482.3zM160 96c-8.8 0-16 7.2-16 16s7.2 16 16 16H288c8.8 0 16-7.2 16-16s-7.2-16-16-16H160z"}
                          = fight_participation.fighter.name
                        - if @fight.winner == fight_participation.fighter
                          .float-end
                            %i.fa-solid.fa-trophy
                    .card-body.text-white.fs-6.p-3
                      %ul.list-group.list-group-flush.price-list
                        %li.list-group-item.border-secondary-subtle
                          %p
                            %span.fw-semibold
                              Points De Vie:
                            = fight_participation.fighter.life_points
                        %li.list-group-item.border-secondary-subtle
                          %span.fw-semibold
                            Points D'Attaque:
                          = fight_participation.fighter.attack_points
                        - if fight_participation.equipments.weapon.any?
                          - fight_participation.equipments.weapon.each do |weapon|
                            %li.list-group-item.border-secondary-subtle
                              %p
                                %span.fw-semibold
                                  =weapon.name
                              %span.fw-semibold
                                Point D'Attaque:
                              = weapon.attack_points
                              %span.fw-semibold
                                Point De Defense:
                              = weapon.defense_points
                        - if fight_participation.equipments.shield.any?
                          - fight_participation.equipments.shield.each do |shield|
                            %li.list-group-item.border-secondary-subtle
                              %p
                                %span.fw-semibold
                                  =shield.name
                              %span.fw-semibold
                                Point De Defense:
                              = shield.defense_points
                              %span.fw-semibold
                                Point D'Attaque:
                              = shield.attack_points
                - if index.zero?
                  .col-md-2.align-self-center.text-center
                    VS
            %h3.text-center= "Historique de Attaques"
            .card.mb-4
              %ul.list-group.list-group-flush
                - @fight.hits.order(:id).each do |hit|
                  -if hit.fight_participation == @fight.fight_participations.second
                    %li.list-group-item.border-secondary-subtle.text-end
                      %span.badge.bg-danger
                        = hit.damage
                      - if hit.fight_participation_weapon.present?
                        = hit.fight_participation_weapon.equipment.name
                        %span.badge.bg-danger
                          %i.fa-solid.fa-gun
                      = hit.fight_participation.fighter.name
                      %span.badge.bg-info
                        %i.fa-solid.fa-person-rifle
                  -else
                    %li.list-group-item.border-secondary-subtle
                      %span.badge.bg-info
                        %i.fa-solid.fa-person-rifle
                      = hit.fight_participation.fighter.name
                      - if hit.fight_participation_weapon.present?
                        %span.badge.bg-danger
                          %i.fa-solid.fa-gun
                        = hit.fight_participation_weapon.equipment.name
                      %span.badge.bg-danger
                        = hit.damage